FROM alpine:latest

ARG PB_VERSION=0.11.2

RUN apk add --no-cache \
  unzip \
  openssh

# Download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

COPY pb_migrations /pb/pb_migrations/

EXPOSE 8080

# Run migrations first
RUN ["/pb/pocketbase", "migrate"]

# Start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]