name: Fly Deploy
on:
  push:
    branches: ['master']
    paths:
      - 'pb/*'
  pull_request:
    branches: ['master']
    paths:
      - 'pb/*'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        working-directory: ./pb
